image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/
    - ${PRE_COMMIT_HOME}
    - ${PIP_CACHE_DIR}

stages:
  - config
  - format
  - linting
  - typing

before_script:
  - python -V  # Print out python version for debugging
  - pip install poetry
  - virtualenv venv
  - source venv/bin/activate
  - poetry install

markdown:
  stage: config
  script:
    - pre-commit run markdownlint

toml:
  stage: config
  script:
    - pre-commit run check-toml

yaml:
  stage: config
  script:
    - pre-commit run yamllint

trailing_whitespace:
  stage: format
  script:
    - pre-commit run trailing-whitespace

eol_fixer:
  stage: format
  script:
    - pre-commit run end-of-line-files

black:
  stage: format
  script:
    - pre-commit run black

isort:
  stage: format
  script:
    - pre-commit run isort

autoflake:
  stage: linting
  script:
    - pre-commit run autoflake

bandit:
  stage: linting
  script:
    - pre-commit run bandit

pylint:
  stage: linting
  script:
    - pre-commit run pylint

mypy:
  stage: typing
  script:
    - pre-commit run mypy
